### ISSUE TITLE
Configurable phantomjs binary filename

### ISSUE THREAD

**Issue by topsy-turvy** [klieber/phantomjs-maven-plugin#25]
It would be nice to be able to specify phantomjs binary path without invoking 'install' goal.

Currently jasmine-maven-plugin relies on ${phantomjs.binary} property set by phantomjs-maven-plugin within 'install' goal. While it is okay for CI build, it makes impossible to run jasmine-maven-plugin:test goal separately on developer host. Right now it is possible to specify 'outputDirectory' property but the final path will be OS specific anyway (phantomjs.exe vs phantomjs). I suggest to add 'outputBinaryPath' which will be the final full path of binary including executable filename. I.e.

`<outputBinaryPath>`target/phantomjs-dir/custom-phantomjs-name`</outputBinaryPath>`

means to extract binary to '${project.dir}/target/phantomjs-dir', rename 'phantomjs' to 'custom-phantomjs-name' and grant it executable rights. This way 'install' goal on developer host can be run only once and will extract binary to predictable path. Then jasmine:test goal can be used with specified 'phantomjs.binary.path' equals to 'outputBinaryPath' value.

**Comment by klieber** [comment]
@topsy-turvy Sorry for taking so long to respond to this.  If you're not going to use the plugin to do the install then just either pass the property via command line or have the developers set it in their maven `settings.xml`.

So you could do this:
```
mvn jasmine:test -Dphantomjs.binary.path=/usr/bin/phantomjs
```
Or you could even do this:
```
mvn phantomjs:install jasmine:test
```

Or finally just add this to your maven `settings.xml`:

```
  <profiles>
    <profile>
      <id>phantomjs</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <phantomjs.binary.bath>/usr/bin/phantomjs</phantomjs.binary.bath>
      </properties>
    </profile>
  </profiles>
```
