### ISSUE TITLE
update phantomjs to 2.0

### ISSUE THREAD

**Issue by mprins** [klieber/phantomjs-maven-plugin#29]
A few days ago version 2 of phantomjs was released. Not all builds are available yet, but just making a note of this.

release notes: http://phantomjs.org/release-2.0.html

also note that there are some regressions.

**Comment by GabiDee** [comment]
+1 vote for the update

**Comment by klieber** [comment]
I've [uploaded](https://repo1.maven.org/maven2/com/github/klieber/phantomjs/2.0.0/) the windows and mac binaries. However, I would not recommend using `2.0.0` right now.  There is currently no binary for linux and there seem to be [problems](https://github.com/ariya/phantomjs/issues/12900#issuecomment-74073057) with the mac binary.
