### ISSUE TITLE
Maven 3.0x compatibility

### ISSUE THREAD

**Issue by Matthias-Ni** [klieber/phantomjs-maven-plugin#30]
Hello, 

is it really neccesary for your library to use Maven 3.1 as minumim requierement? We use Maven 3.0x and it is not possible for us to upgrade to a newer version. :-(

**Comment by klieber** [comment]
If you are able to get it to work on both without issues, send me a pull request and I'll merge it in.

**Comment by monsendag** [comment]
I'm having a similar issue using Maven 3.2.3. Would be happy to test that the plugin works with it, but then I'd have to override the prerequisite field somehow. Any ideas?

By the way, it seems that the prerequisite field is deprecated: http://stackoverflow.com/questions/18055009/enforcing-maven-3-when-to-use-maven-enforcer-plugin-when-to-use-pom-prerequis

**Comment by monsendag** [comment]
Sorry, my mistake. I thought the prerequisite field had an upper bound, but I was using the bundled version in Intellij, which was 3.0.5. Switching to system Maven (3.2.3) solved it.
