### ISSUE TITLE
PhantomJS 2.0.0 archive broken

### ISSUE THREAD

**Issue by leonard84** [klieber/phantomjs-maven-plugin#31]
When using the version 2.0.0 of phantomjs the plugin will fail with

`de.schlichtherle.truezip.fs.FsEntryNotFoundException: zip:file:~/.m2/repository/com/github/klieber/phantomjs/2.0.0/phantomjs-2.0.0-windows.zip!/phantomjs-2.0.0-windows/phantomjs.exe (no such entry)`

The problem is that phantomjs.exe is now in the `phantomjs-2.0.0-windows/bin` subdirectory in the `phantomjs-2.0.0-windows.zip` instead of the `phantomjs-2.0.0-windows` directory.

Only tested on windows.

**Comment by ChuanyuWang** [comment]
We met the same issue as above, the phantomjs package structure has been changed, the .exe is under phantomjs-2.0.0-windows/bin subdirectory of phantomjs-2.0.0-windows.zip
