### ISSUE TITLE
Correct usage of the plugin

### ISSUE THREAD

**Issue by dalexandrov** [klieber/phantomjs-maven-plugin#32]
Hello,

in order to automate PhantomJS tests I found your plug-in.
As far as I see from the docs, I just need to add this to my pom.xml
```
 <build>
    <plugins>
      <plugin>
        <groupId>com.github.klieber</groupId>
        <artifactId>phantomjs-maven-plugin</artifactId>
        <version>${phantomjs-maven-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>install</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <version>1.9.7</version>
        </configuration>
      </plugin>
    </plugins>
 </build>
```
And then I expect all Phantom JS binaries to be downloaded and the tests to run smoothly. 
But each time I run them I get:
java.lang.IllegalStateException: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable

Only if I set explicidly the PATH variable to point the target folder with the binaries with PhantomJS, but thats not the option. 

Am I doing something wrong? Thanks!

**Comment by klieber** [comment]
Please see the [readme](https://github.com/klieber/phantomjs-maven-plugin/blob/master/README.md). There is an example of using the plugin with a JUnit test.
