### ISSUE TITLE
Error when using this plugin

### ISSUE THREAD

**Issue by vandanagopal** [klieber/phantomjs-maven-plugin#33]
Hi,
I get the error below when I added the plugin to my pom.xml file - 
[ERROR] 1) Could not find a suitable constructor in com.github.klieber.phantomjs
.mojo.InstallPhantomJsMojo. Classes must have either one (and only one) construc
tor annotated with @Inject or a zero-argument constructor that is not private.
[ERROR] at com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo.class(Unknown
Source)
Is there anything I should configure that would fix this issue?

**Comment by klieber** [comment]
Which version of the plugin are you using? If it's 0.6 or 0.7 can you try 0.5 and see if that works for you?

**Comment by vandanagopal** [comment]
Sorry, it looks like the problem was with using Maven 3.0.2 with your plugin version 0.6. 
As soon as I upgraded to Maven 3.2, everything worked fine even with version 0.6.
Thanks for the quick response.

**Comment by vandanagopal** [comment]
Although, maybe this should be fixed for maven version < 3.1?

**Comment by klieber** [comment]
Maven versions less than 3.1 are not supported.

**Comment by vandanagopal** [comment]
Ok thanks, I missed that.
