### ISSUE TITLE
Missing binary phantomjs-2.0.0-macosx-fix01.zip 

### ISSUE THREAD

**Issue by ricksbrown** [klieber/phantomjs-maven-plugin#38]
The binary `phantomjs-2.0.0-macosx-fix01.zip ` is found here:
https://repo1.maven.org/maven2/com/github/klieber/phantomjs/2.0.0/

but not here:
https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by klieber** [comment]
Sorry to be just replying to this now. There was a problem with the official mac version of 2.0.0. I don't remember the specifics but this is a patched version so no it is not on the official bitbucket repo. 

I don't recommend 2.0.0 anyways. Go with 1.9.8 or try out the newly released 2.1.1 which seems to be a lot more stable than 2.0.0.
