### ISSUE TITLE
PhantomJS release v2.1.1

### ISSUE THREAD

**Issue by RichardBradley** [klieber/phantomjs-maven-plugin#42]
PhantomJS has released ver 2.1, 

http://phantomjs.org/releases.html
> PhantomJS 2.1 was released on January 23, 2016. It came with an updated WebKit library based on Qt 5.5.

The download page has 2.1.1 http://phantomjs.org/download.html

Please could you bundle this up for `phantomjs-maven-plugin` and update here when it's ready?

(I'd submit a PR, but I don't know how to for this.)

**Comment by mikeapr4** [comment]
+1

**Comment by shaehnel** [comment]
+1

**Comment by hennr** [comment]
It already works.

Try it:

    <plugin>
        <groupId>com.github.klieber</groupId>
        <artifactId>phantomjs-maven-plugin</artifactId>
        <version>0.7</version>
        <executions>
            <execution>
                <goals>
                    <goal>install</goal>
                </goals>
            </execution>
        </executions>
        <configuration>
            <version>2.1.1</version>
        </configuration>
    </plugin>

**Comment by shaehnel** [comment]
My bad, works for me now. Our local Nexus had problems.

**Comment by klieber** [comment]
Sorry I'm just looking at this now, but as others have noted `2.1.1` should be in maven central as of 1/28/2016:

http://search.maven.org/#artifactdetails%7Ccom.github.klieber%7Cphantomjs%7C2.1.1%7CN%2FA
