### ISSUE TITLE
Error while loading shared libraries: libfreetype.so.6

### ISSUE THREAD

**Issue by ashokmadi** [klieber/phantomjs-maven-plugin#49]
I am using this plugin with phantomjs version 1.9.2, Java 1.6 and maven 3.2. It works well in my local eclipse set up. When I run this on bamboo CI build, it throws following error:

"target/phantomjs-maven-plugin/phantomjs-1.9.2-linux-i686/bin/phantomjs: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory"

Here is the pom.xml plugin details:

```
<plugin>
	<groupId>com.github.klieber</groupId>
	<artifactId>phantomjs-maven-plugin</artifactId>
	<version>0.7</version>
	<executions>
		<execution>
			<goals>
				<goal>install</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<version>1.9.2</version>
	</configuration>
</plugin>
```

Am I missing any thing or doing something wrong. Any suggestions or help on this would be much appreciated.

Thanks

**Comment by klieber** [comment]
This sounds like an issue with phantomjs and not with the plugin.  I would suggest installing phantomjs manually on your CI server and see if phantomjs can be executed.  If a manual install doesn't work then you should open an issue with the phantomjs project.  If it does work then I'll have to think on it some more.

**Comment by klieber** [comment]
Closing this issue since there hasn't been any further comments.
