### ISSUE TITLE
Supported latest released PhantomJS

### ISSUE THREAD

**Issue by smurf667** [klieber/phantomjs-maven-plugin#50]
Hello Kyle,

it seems a bug troubling many people has finally been adressed: https://github.com/ariya/phantomjs/issues/12750
The fix should be contained in the [release 2.1.13](https://github.com/amir20/phantomjs-node/releases/tag/v2.1.13)

It would be highly appreciated if the Maven plugin could use version 2.1.13 on Linux.

**Comment by klieber** [comment]
@smurf667, not sure I understand.  The bug you referenced is still open and the release you are linking to is not a phantomjs release.  That is `phantomjs-node` which is an npm module that provides similar functionality that the `phantomjs-maven-plugin` provides but in a NodeJS environment.  So, I'm not sure what that has to do with this plugin.  As far as I can see the latest version of PhantomJS is still 2.1.1 which is already supported by the plugin: http://repo1.maven.org/maven2/com/github/klieber/phantomjs/2.1.1/

**Comment by klieber** [comment]
Sorry, closed this accidentally.  I'll give you some time to respond to my last comment before closing it.

**Comment by smurf667** [comment]
Hi Kyle, yes sorry. It appears the discussion is still ongoing. My request
was premature.
