### ISSUE TITLE
phantomjs 2.5 beta

### ISSUE THREAD

**Issue by chapmanc** [klieber/phantomjs-maven-plugin#51]
Is there any chance you could add the binaries from 2.5beta to your archive?

https://bitbucket.org/ariya/phantomjs/downloads

**Comment by chapmanc** [comment]
@klieber any chance to look at this? Let me know if there is anything I can do to make it happen

**Comment by chapmanc** [comment]
@klieber are you still maintaining this? Please let me know.

**Comment by paulpach** [comment]
I would like to see this happen too.  Right now even if I specify the url it is broken because phantomjs is compressed with different folder structure.

**Comment by klieber** [comment]
@chapmanc @paulpach, I am still maintaining this project. However, I don't really consider uploading a beta version of phantomjs a priority.  As soon as the release of 2.5 is out I will definitely have it available as soon as possible.  If there are issues with the folder structure in the beta you are welcome to send me a pull request with any changes that are needed to make it work (ensuring the old structure still works as well of course).

**Comment by chapmanc** [comment]
Hey @klieber . Thanks for the reply. Normally I would totally agree with you but 2.5 is a monumental jump forward as we can now execute es6 code within phantomjs. This is huge for us and it will really move code forward. This shouldn't be too difficult as it's only pushing a binary up. Any chance you would reconsider?

**Comment by klieber** [comment]
@chapmanc As I said.  Pull requests are welcome.

**Comment by joycollector** [comment]
2.5.0-beta version still has problems running on MacOS OOTB. Please see: https://github.com/ariya/phantomjs/issues/14819

But this PR (https://github.com/klieber/phantomjs-maven-plugin/issues/53) should fix versioning issues.

**Comment by klieber** [comment]
This project is no longer being actively maintained.
